[package]
name = "risp"
version = "0.1.0"
authors = ["Chris <chris.clark@coffeeb4code.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
